import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavbarFooter from './components/Footer/NavbarFooter'
import Navbar from './components/Header/Navbar'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`inter.className
      w-full h-screen flex flex-col justify-center items-center gap-5 bg-green-100
      `}>
        <Navbar />
        {children}
        <NavbarFooter />
      </body>
    </html>
  )
}
